name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run Migrations
        run: npm run migrate
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DIALECT: ${{ secrets.MYSQL_DIALECT }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and Deploy
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
        run: |
          gcloud config set project $PROJECT_ID
          gcloud builds submit --config cloudbuild.yaml .