name: GAC Deployment

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm i

    - name: Run Migrations
      run: npm run migrate
      env:
        PORT: 5000
        MYSQL_HOST: ${{ MYSQL_HOST }}
        MYSQL_DATABASE: ${{ MYSQL_DATABASE }}
        MYSQL_USERNAME: ${{ MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ MYSQL_PASSWORD }}
        MYSQL_DIALECT: ${{ MYSQL_DIALECT }}
        ACCESS_TOKEN_KEY: ${{ ACCESS_TOKEN_KEY }}
        REFRESH_TOKEN_KEY: ${{ REFRESH_TOKEN_KEY }}
    
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.standard.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"