name: GCAE Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Container to Google Cloud App Engine
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file=${{ secrets.GCR_TOKEN }}

    - name: Docker auth
      run: |-
        gcloud auth configure-docker

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT }}/backend:${{ github.sha }}
        registry: gcr.io
        credentials: ${{ secrets.GCR_TOKEN }}

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: gcr.io/${{ secrets.GCP_PROJECT }}/backend:${{ github.sha }}
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"