name: GCAE Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT }}/backend:${{ github.sha }}
        registry: gcr.io
        credentials: ${{ secrets.GCR_TOKEN }}

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: gcr.io/${{ secrets.GCP_PROJECT }}/backend:${{ github.sha }}
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"