name: GCCR Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT }}/backend:${{ github.sha }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Run Cloud Build
      run: |
        gcloud builds submit --config=cloudbuild.yaml .

    - name: Test
      run: |
        gcloud run services describe backend --format 'value(status.url)'